services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: ..             # go up one level where Dockerfile lives
      dockerfile: dockerfile  # relative to that context
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017
      DB_NAME: notes_multi_tenant
      HEADER_ORG: X-Org-ID
      HEADER_USER: X-User-ID
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  mongo_data:
